# Utiliser l'image PHP 8.0 avec Apache
FROM php:8.1-apache

# Installation des dépendances nécessaires
RUN apt-get update && apt-get install -y \
    libzip-dev \
    unzip \
    git \
    && docker-php-ext-install zip pdo_mysql

# Configuration d'Apache pour Laravel
RUN a2enmod rewrite

# Définir le répertoire de travail dans le conteneur
WORKDIR /var/www/html

# Copier les fichiers de l'application dans le conteneur
COPY . .

# Installation des dépendances PHP avec Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
#RUN composer update
RUN apt-get update
RUN composer install --no-interaction || true

# Configuration des permissions
RUN chmod -R 777 /var/www/html/storage /var/www/html/bootstrap/cache /var/www/html
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache /var/www/html

# Exposer le port 80 du conteneur
EXPOSE 80

# Commande par défaut pour démarrer Apache
CMD ["apache2-foreground"]
