version: '3'

services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge
